"""Extract page images from PDF files.

Uses PyMuPDF (fitz) to extract Go board images from PDF files.
Supports two extraction strategies:

1. **Embedded images** — PDF pages with a single embedded raster image
   (e.g., PDFs generated by ReportLab/tsumego-pdf).  Extracts the raw
   image without re-rendering.

2. **Rendered pages** — Fallback: rasterises each page at a configurable
   DPI.  Works with any PDF but may be slower and lower quality.

Usage:
    from tools.pdf_to_sgf.pdf_extractor import extract_pages

    pages = extract_pages("path/to/book.pdf")
    for page_num, img in pages:
        print(f"Page {page_num}: {img.size}")
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

import fitz  # PyMuPDF
from PIL import Image
import io

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class ExtractionConfig:
    """Configuration for PDF page extraction."""

    render_dpi: int = 200
    """DPI for page rendering fallback."""

    min_image_area: int = 50_000
    """Minimum pixel area to consider an embedded image (skip tiny icons)."""

    prefer_embedded: bool = True
    """If True, try extracting embedded images before rendering pages."""


_DEFAULT_CONFIG = ExtractionConfig()


@dataclass(frozen=True)
class ExtractedPage:
    """A single extracted page/image from a PDF."""

    page_number: int
    """1-based page number."""

    image: Image.Image
    """Extracted image as PIL Image (RGB)."""

    source: str
    """Extraction method: 'embedded' or 'rendered'."""

    width: int
    height: int

    @property
    def size(self) -> tuple[int, int]:
        return (self.width, self.height)


def extract_pages(
    pdf_path: str | Path,
    config: ExtractionConfig = _DEFAULT_CONFIG,
    *,
    page_range: tuple[int, int] | None = None,
) -> list[ExtractedPage]:
    """Extract page images from a PDF file.

    Parameters
    ----------
    pdf_path : str or Path
        Path to the PDF file.
    config : ExtractionConfig
        Extraction settings.
    page_range : tuple[int, int] or None
        Optional 1-based inclusive page range (start, end).
        If None, extracts all pages.

    Returns
    -------
    list[ExtractedPage]
        Extracted pages with images.
    """
    pdf_path = Path(pdf_path)
    if not pdf_path.exists():
        raise FileNotFoundError(f"PDF not found: {pdf_path}")

    doc = fitz.open(str(pdf_path))
    pages: list[ExtractedPage] = []

    start = (page_range[0] - 1) if page_range else 0
    end = page_range[1] if page_range else len(doc)
    end = min(end, len(doc))

    log.info("Extracting pages %d-%d from %s (%d total pages)",
             start + 1, end, pdf_path.name, len(doc))

    for i in range(start, end):
        page = doc[i]
        page_num = i + 1

        extracted = None
        if config.prefer_embedded:
            extracted = _try_extract_embedded(doc, page, page_num, config)

        if extracted is None:
            extracted = _render_page(page, page_num, config)

        if extracted is not None:
            pages.append(extracted)

    doc.close()
    log.info("Extracted %d pages from %s", len(pages), pdf_path.name)
    return pages


def _try_extract_embedded(
    doc: fitz.Document,
    page: fitz.Page,
    page_num: int,
    config: ExtractionConfig,
) -> ExtractedPage | None:
    """Try to extract a single large embedded image from the page."""
    img_list = page.get_images(full=True)

    # Filter for substantial images
    candidates = []
    for img_info in img_list:
        xref = img_info[0]
        try:
            base_img = doc.extract_image(xref)
        except Exception:
            continue

        w, h = base_img["width"], base_img["height"]
        if w * h >= config.min_image_area:
            candidates.append((xref, base_img, w, h))

    if not candidates:
        return None

    # Use the largest image on the page
    candidates.sort(key=lambda c: c[2] * c[3], reverse=True)
    _, base_img, w, h = candidates[0]

    img_bytes = base_img["image"]
    pil_img = Image.open(io.BytesIO(img_bytes)).convert("RGB")

    log.debug("Page %d: extracted embedded %dx%d image", page_num, w, h)
    return ExtractedPage(
        page_number=page_num,
        image=pil_img,
        source="embedded",
        width=pil_img.width,
        height=pil_img.height,
    )


def _render_page(
    page: fitz.Page,
    page_num: int,
    config: ExtractionConfig,
) -> ExtractedPage:
    """Render a page to a raster image at the configured DPI."""
    mat = fitz.Matrix(config.render_dpi / 72, config.render_dpi / 72)
    pix = page.get_pixmap(matrix=mat)

    img_bytes = pix.tobytes("png")
    pil_img = Image.open(io.BytesIO(img_bytes)).convert("RGB")

    log.debug("Page %d: rendered at %d DPI (%dx%d)",
              page_num, config.render_dpi, pil_img.width, pil_img.height)
    return ExtractedPage(
        page_number=page_num,
        image=pil_img,
        source="rendered",
        width=pil_img.width,
        height=pil_img.height,
    )
