"""
Rollback functionality for YenGo puzzle collection.

Delete SGF files and rebuild inventory.  Index databases are
regenerated by re-running the publish pipeline.  Git is the backup.

Usage:
    manager = RollbackManager(output_dir, log_reader)
    result = manager.rollback_by_run(run_id, dry_run=False)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

from backend.puzzle_manager.core.content_db import delete_entries, read_all_entries
from backend.puzzle_manager.core.fs_utils import remove_empty_directories
from backend.puzzle_manager.inventory.manager import InventoryManager
from backend.puzzle_manager.inventory.reconcile import reconcile_inventory
from backend.puzzle_manager.models.publish_log import PublishLogEntry
from backend.puzzle_manager.pipeline.lock import PipelineLock
from backend.puzzle_manager.publish_log import PublishLogReader

logger = logging.getLogger("puzzle_manager.rollback")


class RollbackError(Exception):
    """Raised when rollback fails."""
    pass


@dataclass
class RollbackResult:
    """Result of a rollback operation."""

    success: bool = False
    dry_run: bool = False
    puzzles_affected: int = 0
    files_deleted: int = 0
    index_rebuilt: bool = False
    errors: list[str] = field(default_factory=list)

    def summary(self) -> str:
        """Human-readable summary."""
        action = "Would affect" if self.dry_run else "Affected"
        lines = [
            f"{action} {self.puzzles_affected} puzzles",
            f"Files deleted: {self.files_deleted}",
        ]
        if self.errors:
            lines.append(f"Errors: {len(self.errors)}")
        return "\n".join(lines)


class RollbackManager:
    """Rollback manager.

    Rollback flow:
    1. Acquire PipelineLock
    2. Query publish log for entries matching run_id
    3. Delete SGF files
    4. Rebuild inventory from disk
    5. Release lock

    Note: Index databases must be regenerated by re-running the publish
    pipeline after rollback.
    """

    def __init__(
        self,
        output_dir: Path,
        log_reader: PublishLogReader,
        max_batch_size: int = 10_000,
    ) -> None:
        self.output_dir = output_dir
        self.log_reader = log_reader
        self.max_batch_size = max_batch_size

    def rollback_by_run(
        self,
        run_id: str,
        *,
        dry_run: bool = False,
    ) -> RollbackResult:
        """Rollback all puzzles from a specific pipeline run.

        Args:
            run_id: Pipeline run ID to rollback.
            dry_run: If True, preview without making changes.

        Returns:
            RollbackResult with outcome details.
        """
        entries = self.log_reader.search_by_run_id(run_id)
        if not entries:
            return RollbackResult(
                success=True,
                dry_run=dry_run,
                errors=[f"No publish log entries found for run_id={run_id}"],
            )

        if len(entries) > self.max_batch_size:
            return RollbackResult(
                success=False,
                errors=[
                    f"Rollback would affect {len(entries)} puzzles "
                    f"(max={self.max_batch_size}). Use smaller batches."
                ],
            )

        return self._execute(entries, dry_run=dry_run)

    def _execute(
        self,
        entries: list[PublishLogEntry],
        *,
        dry_run: bool = False,
    ) -> RollbackResult:
        """Execute the rollback: delete files + rebuild indexes.

        Args:
            entries: Publish log entries to roll back.
            dry_run: If True, preview only.

        Returns:
            RollbackResult.
        """
        result = RollbackResult(dry_run=dry_run, puzzles_affected=len(entries))

        if dry_run:
            result.success = True
            return result

        # Acquire pipeline lock
        lock = PipelineLock(run_id="rollback")
        lock.acquire()

        try:
            # 1. Delete SGF files
            deleted = 0
            for entry in entries:
                sgf_path = self.output_dir / entry.path
                if sgf_path.exists():
                    sgf_path.unlink()
                    deleted += 1
                    logger.debug("Deleted: %s", entry.path)
                else:
                    logger.warning("File not found (already deleted?): %s", entry.path)

            result.files_deleted = deleted

            # Remove empty batch directories
            sgf_dir = self.output_dir / "sgf"
            if sgf_dir.exists():
                remove_empty_directories(sgf_dir)

            # 2. Clean DB-2: remove rolled-back entries from content database
            rolled_back_hashes = [
                e.puzzle_id for e in entries if e.puzzle_id
            ]
            content_db_path = self.output_dir / "yengo-content.db"
            if rolled_back_hashes and content_db_path.exists():
                db2_deleted = delete_entries(content_db_path, rolled_back_hashes)
                logger.info("Cleaned %d entries from content DB", db2_deleted)

            # 3. Rebuild DB-1: regenerate search database from remaining DB-2 entries
            self._rebuild_search_db()
            result.index_rebuilt = True

            # 4. Rebuild inventory from disk
            self._rebuild_inventory()

            result.success = True
            logger.info(
                "Rollback complete: %d files deleted, index rebuilt",
                deleted,
            )

        except Exception as e:
            result.success = False
            result.errors.append(str(e))
            logger.error("Rollback failed: %s", e, exc_info=True)

        finally:
            lock.release()

        return result

    def _rebuild_search_db(self) -> None:
        """Rebuild search database (DB-1) from content database (DB-2) after rollback."""
        try:
            import json
            import os

            from backend.puzzle_manager.core.db_builder import build_search_db
            from backend.puzzle_manager.core.db_models import (
                CollectionMeta,
                PuzzleEntry,
                sgf_to_puzzle_entry,
            )
            from backend.puzzle_manager.core.id_maps import IdMaps

            content_db_path = self.output_dir / "yengo-content.db"
            db_path = self.output_dir / "yengo-search.db"
            version_path = self.output_dir / "db-version.json"

            db2_rows = read_all_entries(content_db_path)
            if not db2_rows:
                # No entries remain — remove DB-1
                if db_path.exists():
                    db_path.unlink()
                if version_path.exists():
                    version_path.unlink()
                logger.info("No entries remain; search DB removed")
                return

            id_maps = IdMaps.load()
            entries: list[PuzzleEntry] = []
            for row in db2_rows:
                try:
                    sgf_content = row["sgf_content"]
                    if not sgf_content:
                        continue
                    ch = row["content_hash"]
                    entry = sgf_to_puzzle_entry(
                        sgf_content, ch, id_maps, self.output_dir,
                        batch_hint=row.get("batch"),
                        source=row.get("source", ""),
                    )
                    if entry is not None:
                        entries.append(entry)
                except Exception as e:
                    logger.debug("Failed to convert DB-2 entry %s: %s", row.get("content_hash", "?"), e)

            # Load collections from config
            from backend.puzzle_manager.paths import get_global_config_dir
            config_path = get_global_config_dir() / "collections.json"
            collections: list[CollectionMeta] = []
            if config_path.exists():
                data = json.loads(config_path.read_text(encoding="utf-8"))
                for col in data.get("collections", []):
                    collections.append(CollectionMeta(
                        collection_id=col["id"],
                        slug=col["slug"],
                        name=col["name"],
                        category=col.get("type"),
                    ))

            # Edition detection: split multi-source collections into editions
            from backend.puzzle_manager.core.edition_detection import create_editions
            edition_cols = create_editions(entries, collections, content_db_path)
            collections.extend(edition_cols)

            # Build deterministic sequence_map
            from collections import defaultdict as _defaultdict
            _col_entries: dict[int, list[str]] = _defaultdict(list)
            for e in entries:
                for col_id in e.collection_ids:
                    _col_entries[col_id].append(e.content_hash)
            _sequence_map: dict[tuple[str, int], int] = {}
            for col_id, hashes in _col_entries.items():
                for seq, ch in enumerate(sorted(hashes), start=1):
                    _sequence_map[(ch, col_id)] = seq

            # Build to temp file then atomic swap (Issue 2)
            tmp_db_path = db_path.with_suffix('.db.tmp')
            if tmp_db_path.exists():
                tmp_db_path.unlink()

            # Rollback/reconcile generated_at uses datetime.now(UTC) — accepted
            # deviation from pure determinism for non-pipeline operations (RC-4).
            version_info = build_search_db(
                entries=entries,
                collections=collections,
                output_path=tmp_db_path,
                sequence_map=_sequence_map,
            )

            # Atomic swap
            os.replace(str(tmp_db_path), str(db_path))

            # Atomic write for version file (RC-2)
            tmp_version_path = version_path.with_suffix('.json.tmp')
            tmp_version_path.write_text(
                json.dumps(version_info.to_dict(), indent=2),
                encoding="utf-8",
            )
            os.replace(str(tmp_version_path), str(version_path))
            logger.info(
                "Search DB rebuilt after rollback: %d puzzles, version=%s",
                version_info.puzzle_count, version_info.db_version,
            )

            # Regenerate daily schedules for the last 90 days (backward from today)
            from datetime import timedelta

            from backend.puzzle_manager.core.datetime_utils import utc_now
            from backend.puzzle_manager.daily.db_writer import (
                inject_daily_schedule,
                prune_daily_window,
            )
            from backend.puzzle_manager.daily.generator import DailyGenerator
            try:
                today = utc_now()
                start_date = today - timedelta(days=89)
                generator = DailyGenerator(db_path=db_path)
                result = generator.generate(start_date=start_date, end_date=today, force=True)
                if result.challenges:
                    inject_daily_schedule(db_path, result.challenges)
                    prune_daily_window(db_path, generator.config.rolling_window_days)
                    logger.info("Rollback daily: regenerated %d schedule(s)", len(result.challenges))
            except Exception as daily_err:
                logger.warning("Rollback daily regeneration failed (non-fatal): %s", daily_err)

        except Exception as e:
            logger.warning("Failed to rebuild search DB after rollback: %s", e)

    def _rebuild_inventory(self) -> None:
        """Rebuild inventory from disk after rollback."""
        try:
            inventory = reconcile_inventory(output_dir=self.output_dir, run_id="rollback")
            ops_dir = self.output_dir / ".puzzle-inventory-state"
            ops_dir.mkdir(parents=True, exist_ok=True)
            inv_path = ops_dir / "inventory.json"
            manager = InventoryManager(inventory_path=inv_path)
            manager.save(inventory)
            logger.info(
                "Inventory rebuilt after rollback: %d puzzles",
                inventory.collection.total_puzzles,
            )
        except Exception as e:
            logger.warning("Failed to rebuild inventory after rollback: %s", e)
