STATIC_MAJOR_REV = 2;
STATIC_SW_REV = 2;
STATIC_DB_REV = 1;
STATIC_PUBLIC_COUNT = 2246;
STATIC_ICONS = ["dog", "dragon", "goat", "horse", "monkey", "ox", "pig", "rabbit", "rat", "rooster", "snake", "tiger"];
STATIC_COLORS = ["black", "white", "red", "green", "blue", "purple"];
STATIC_MAX_FAILED_DATA_LENGTH = 100000;
STATIC_MAX_VISITOR_HISTORY_LENGTH = 50000;
STATIC_MAX_VISITOR_FAVORITES_LENGTH = 50000;
STATIC_HASH_LENGTHS = [0, 2, 2, 4, 6, 8, 12, 14, 20, 24, 30, 36, 42, 50, 56, 66, 74, 84, 94, 104];

STATIC_SERVER_MODE = "production"; // Legal values: "development" or "production"

// Todo: The following is temporary used until endgame ranks have settled:
STATIC_ENDGAME_RANKS = {
  "rating_span": [
    {"min": 0, "max": 99, "label": "beginner"},
    {"min": 100, "max": 549, "label": "span-based"},
    {"min": 550, "max": 1149, "label": "span-based"},
    {"min": 1150, "max": 1549, "label": "span-based"},
    {"min": 1550, "max": 2049, "label": "span-based"},
    {"min": 2050, "max": 2649, "label": "span-based"},
    {"min": 2650, "max": 2849, "label": "pro"},
    {"min": 2850, "max": 3000, "label": "ai"},
  ],
  "get_span_from_rating": function(rating) {
    if (isNaN(rating)) {
      return null;
    }
    for (var s of this.rating_span) {
      if (rating >= s.min && rating <= s.max) {
        return s;
      }
    }
  },
};

STATIC_UI_THEMES = [
    "dark",
    "light",
];

STATIC_USER_DATA_KEYS = [
    "session_key",
    "verified_id",
    "verified_avatar",
    "verified_color",
    "verified_rating",
    "verified_user",
    "verified_admin",
    "statistics",
    "expansion_pack",
    "last_loaded",
    "attempted",
    "failed_data",
    "commentor",
    "last_comment",
];

STATIC_CATEGORIES = [
    "attachments",
    "basics",
    "capturing",
    "endgame",
    "eyes",
    "ko",
    "placements",
    "reductions",
    "sacrifice",
    "seki",
    "semeai",
    "shape",
    "shortage",
    "tactics",
    "vital-point",
    ];


STATIC_TAGS = [
    "first-line-attachment",
    "first-line-clamp",
    "first-line-tiger",
    "two-two-attachment",
    "two-two-steal",
    "angle-tesuji",
    "atari",
    "atari-down",
    "attachment",
    "peep-attachment",
    "bamboo-joint",
    "bamboo-removal",
    "belly-attachment",
    "bent-four",
    "blocking",
    "side-block",
    "broken-ladder",
    "bump",
    "capture",
    "choke",
    "clamp",
    "comb",
    "squeeze",
    "under-connection",
    "corner-squeeze-ko",
    "cross-cut",
    "cut",
    "descending",
    "diagonal-tesuji",
    "disconnection",
    "double-atari",
    "double-hane",
    "driving",
    "elephant-weakness",
    "guzumi",
    "extension",
    "eye-denying-placement",
    "vital-eye-point",
    "forcing-ko",
    "hane",
    "hanging-connection",
    "drop-jump",
    "ignoring-atari",
    "inside-job",
    "keima-jump",
    "ko",
    "kosumi",
    "ladder",
    "liberty-cut",
    "monkey-jump",
    "nakade",
    "nose-tesuji",
    "no-throw-atari",
    "oogeima-weakness",
    "peep",
    "pinch",
    "preventing-snapback",
    "push",
    "push-behind",
    "raccoon",
    "give-two",
    "sacrifice",
    "escaping",
    "seki",
    "separating-hane",
    "shape-stealing",
    "damezumari",
    "snapback",
    "table-shape",
    "threatening-snapback",
    "throw-in",
    "tigers-mouth",
    "tombstone",
    "turn",
    "under-the-stones",
    "wedge",
    "ko-fight",
    "wrist-cut",
    "one-two-inside-peep",
    "one-two-bend",
    "liberty-descend",
    "pulling-back",
    "golden-chicken",
    "one-one-double-threat",
    "one-one-kosumi",
    "two-two-throw-in",
    "liberty-atari",
    "corner-pillar",
    "little-mouse",
    "first-line-ponnuki",
    "one-two-belly-placement",
    "corner-ponnuki",
    "crawling",
    "first-line-fill",
    "push-and-cut",
    "peep-and-cut",
    "three-two-steal",
    "keima",
    "one-space-jump",
    "probe",
    "horseshoe",
    "first-line-guzumi",
    "symmetrical-position",
    "cranes-nest",
    "solidifying-eye",
    "falsifying-eye",
    "eye-denying-throw-in",
    "fancy-jump",
    "double-snapback",
    "connect-and-die",
    "creating-shortage",
    "reducing-hane",
    "geta",
    "one-two-keima",
    "backside-attachment",
    "loaded-kosumi",
    "eye-or-cut",
    "threatening-rescue",
    "corner-sacrifice",
    "one-two-throw-in",
    "inside-kosumi",
    "protective-jump",
    "first-line-nose",
    "tetris-hane",
    "recapture-ponnuki",
    "carpenters-square",
    "ten-thousand-year-ko",
    "tetris-placement",
    "one-two-liberty-throw-in",
    "semeai",
    "triple-ko",
    "preventing-double-atari",
    "two-two-double-tiger",
    "feeding-the-tiger",
    "blindspot-throw-in",
    "blindspot-inside-fill",
    "one-one-placement",
    "miai-descend",
    "one-two-double-hane",
    "ai-hane",
    "kangaroo-attachment",
    "two-two-vital-point",
    "large-sacrifice",
    "pyramide-four",
    "bulky-five",
    "bulky-four",
    "rabbity-six",
    "lightning-shape",
    "smothered-ko",
    "straight-three",
    "bent-three",
    "crossed-five",
    "oshitsubushi",
    "double-ko",
    "eye-denying-kosumi",
    "unstoppable-peep",
    "two-two-bend",
    "mouth-shape",
    "placement",
    "mutual-liberty",
    "preventing-nakade",
    "making-eyes",
    "denying-eyes",
    "mirror-symmetry",
    "bolt",
    "eternal-life",
    "farmers-hat",
    ];


